apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE DATABASE PostgresGameData;

    \c PostgresGameData;

    CREATE TABLE PostgresSqlGameHistoryTable (
        transactionId VARCHAR(1000) PRIMARY KEY,
        initPlayer VARCHAR(1000),
        hostPlayer VARCHAR(1000),
        gameId VARCHAR(1000),
        playerLost VARCHAR(1000),
        amountPaid DOUBLE,
        timePaid: TIMESTAMP,
        paymentId: VARCHAR(1000)
    );

    CREATE TABLE public.SingleGames (
      SingleGameId VARCHAR(255) PRIMARY KEY,
      hostPlayer VARCHAR(255),
      guestPlayer VARCHAR(255),
      finalScore INT[],
      inGameScores JSONB,
      timePlayed TIMESTAMP NOT NULL,
      gameEditor VARCHAR(255),
      twitchBroadcasterId VARCHAR(255),
      otherGameInfo JSONB,
      predictionId VARCHAR(255),
      videoFilePath VARCHAR(255)
    );
