apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "user_admin"
        - name: POSTGRES_PASSWORD
          value: "k8sLovers"
        - name: POSTGRES_DB
          value: "postgresgamedata"
        - name: LOCAL_PG_HOST
          value: "localhost"
        - name: LOCAL_PG_PORT
          value: "5432"  # Default port for PostgreSQL

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP  # or NodePort/LoadBalancer if needed

