apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-game-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-game
  template:
    metadata:
      labels:
        app: postgres-game
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
                name: postgres-secrets
                key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: PostgresSqlSingleGameTable
        volumeMounts:
        - name: postgres-game-data
          mountPath: /var/lib/postgresql/singleGame-data
      volumes:
      - name: postgres-game-data
        persistentVolumeClaim:
          claimName: postgres-game-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-game-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP  # or NodePort/LoadBalancer if needed

