apiVersion: apps/v1
kind: Deployment
metadata:
  name: gametransactionapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gametransactionapi
  template:
    metadata:
      labels:
        app: gametransactionapi
    spec:
      containers:
      - name: gametransactionapi
        image: timchoi123/gametransactionapi:latest # Replace with your Docker image and tag
        ports:
        - containerPort: 8086 # Replace with the port your API listens on
        # Add other environment variables or configurations as needed
---
apiVersion: v1
kind: Service
metadata:
  name: gametransactionapi-service
spec:
  selector:
    app: gametransactionapi
  ports:
  - protocol: TCP
    port: 89
    targetPort: 8086 # This should match the containerPort in the Deployment YAML
    nodePort: 30011
  type: NodePort # Change this to NodePort or LoadBalancer if you need external access
