apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc-2
  labels:
    app: sqlserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-volume
  labels:
    type: local
    app: sqlserver
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/mssql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: k8sLovers!
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql/data
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  labels:
    app: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30007
  type: NodePort  # or NodePort/LoadBalancer if needed

